@TrabalhoRaizesDoNordeste_HostAddress = http://localhost:5044

POST {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/
Content-Type: application/json
Accept: application/json
{
  "nomeCategoria": "Comida Salgada"

}

###

DELETE {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/3

###

GET {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/
Content-Type: application/json
Accept: application/json

###

PATCH {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/1
Content-Type: application/json
Accept: application/json
{
  "nomeCategoria": "Doces",
  "categoriaAtiva": false
}