@TrabalhoRaizesDoNordeste_HostAddress = http://localhost:5044

GET {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/buscar?nome=bebidas
Content-Type: application/json
Accept: application/json

###

POST {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/
Content-Type: application/json
Accept: application/json
{
  "nomeCategoria": "Bebidas",
  "categoriaAtiva": true
}

###


PATCH {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/2
Content-Type: application/json
Accept: application/json
{
  "nomeCategoria": "Doces",
  "categoriaAtiva": true
}

###

DELETE {{TrabalhoRaizesDoNordeste_HostAddress}}/api/categorias/2
