@TrabalhoRaizesDoNordeste_HostAddress = http://localhost:5044

GET {{TrabalhoRaizesDoNordeste_HostAddress}}/api/fidelidade/
Content-Type: application/json
Accept: application/json

###

POST {{TrabalhoRaizesDoNordeste_HostAddress}}/api/fidelidade/
Content-Type: application/json
Accept: application/json
{
  "UsuarioId": 3,
  "QtdPontos": 358
}

###

PATCH {{TrabalhoRaizesDoNordeste_HostAddress}}/api/fidelidade/1
Content-Type: application/json
Accept: application/json
{
  "UsuarioId": 3,
  "QtdPontos": 20
}

###

DELETE {{TrabalhoRaizesDoNordeste_HostAddress}}/api/fidelidade/2
