@TrabalhoRaizesDoNordeste_HostAddress = http://localhost:5044


GET {{TrabalhoRaizesDoNordeste_HostAddress}}/api/produtos/
Content-Type: application/json
Accept: application/json

###

POST {{TrabalhoRaizesDoNordeste_HostAddress}}/api/produtos/
Content-Type: application/json
Accept: application/json
{
  "nomeProduto": "Suco de Cajá",
  "descricaoProduto": "Suco natural de cajá, disponível durante o período da safra.",
  "precoUnitario": 9.90,
  "produtoSazonal": true,
  "dataInicioSazonal": "2026-01-26",
  "dataFimSazonal": "2026-03-31",
  "produtoAtivo": true,
  "categoriaId": 1
}

###

PATCH {{TrabalhoRaizesDoNordeste_HostAddress}}/api/produtos/2
Content-Type: application/json
Accept: application/json
{
  "nomeProduto": "Suco de Cajá",
  "descricaoProduto": "Suco natural de cajá, disponível durante o período da safra.",
  "precoUnitario": 12.90,
  "produtoSazonal": true,
  "dataInicioSazonal": "2026-01-26",
  "dataFimSazonal": "2026-03-31",
  "produtoAtivo": true,
  "categoriaId": 1
}

###

DELETE {{TrabalhoRaizesDoNordeste_HostAddress}}/api/produtos/1

