@TrabalhoRaizesDoNordeste_HostAddress = http://localhost:5044


GET {{TrabalhoRaizesDoNordeste_HostAddress}}/api/usuarios/
Content-Type: application/json
Accept: application/json

###

POST {{TrabalhoRaizesDoNordeste_HostAddress}}/api/usuarios/3
Content-Type: application/json
Accept: application/json
{
  "Nome": "Julia Moreno",
  "Email": "ju.moreno@email.com",
  "CPF": "256.899.100-00",
  "Telefone": "(48) 99220-8795",
  "Perfil": 3,
  "Rua": "Rua Fugini",
  "Numero": "789",
  "Complemento": "Apto 201",
  "Bairro": "Centro",
  "Cidade": "Florianópolis",
  "Estado": "SC",
  "CEP": "88206-340",
  "senha": "Senha@888",
  "EstabelecimentoId": 2,
  "ConsentimentoLGPD": true,
  "ParticipaFidelidade": false,
  "UsuarioAtivo": true
}

###

PATCH {{TrabalhoRaizesDoNordeste_HostAddress}}/api/usuarios/3
Content-Type: application/json
Accept: application/json
{
  "Nome": "Julia Moreno",
  "Email": "ju.moreno@email.com",
  "CPF": "256.899.100-00",
  "Telefone": "(48) 99220-8795",
  "Perfil": 0,
  "Rua": "Rua Fugini",
  "Numero": "789",
  "Complemento": "Apto 201",
  "Bairro": "Centro",
  "Cidade": "Florianópolis",
  "Estado": "SC",
  "CEP": "88206-340",
  "senha": "Senha@888",
  "EstabelecimentoId": 2,
  "ConsentimentoLGPD": true,
  "ParticipaFidelidade": false,
  "UsuarioAtivo": true
}

###

DELETE {{TrabalhoRaizesDoNordeste_HostAddress}}/api/usuarios/3